repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0 # ← package.json に記載のバージョンに合わせる
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5 # ← 同上
    hooks:
      - id: prettier
