repos:
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v9.0.0-beta.0' # ← package.json に記載のバージョンに合わせる
      hooks:
          - id: eslint

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v4.0.0-alpha.8' # ← 同上
      hooks:
          - id: prettier
