repos:
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v9.0.0-beta.0' # ← package.json に記載のバージョンに合わせる
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@8.56.0
                - eslint-config-prettier@9.1.0
                - eslint-plugin-import@2.29.1
                - eslint-plugin-react@7.33.2
                - eslint-plugin-react-hooks@4.6.0
                - eslint-plugin-react-refresh@0.4.5
                - eslint-plugin-sort-keys-fix@1.1.2
                - eslint-plugin-typescript-sort-keys@3.1.0

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v4.0.0-alpha.8' # ← 同上
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@3.2.5
                - prettier-plugin-tailwindcss@0.5.11
