services:
    web-prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                - VITE_APP_URL=http://localhost:3000
        image: ${DOCKER_IMAGE}
        env_file:
            - .env.local
        ports:
            - 3000:3000
