FROM oven/bun:latest AS base

WORKDIR /app
ENV NODE_ENV=production

FROM base AS builder

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

RUN bun build main.ts --target=node > main.js

FROM base AS production

COPY --from=builder /app/build ./build
COPY --from=builder /app/main.js ./
COPY server ./server

EXPOSE 3000
ENV PORT 3000

CMD bun run main.js
