FROM oven/bun:slim AS base

WORKDIR /app
ENV NODE_ENV=production

ARG VITE_APP_URL=https://www.hassaku0616.com
ENV VITE_APP_URL=${VITE_APP_URL}

FROM base AS builder

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

RUN bun build main.ts --target=node --minify > main.js

FROM base AS production

COPY --from=builder /app/build ./build
COPY --from=builder /app/main.js ./

EXPOSE 3000
ENV PORT 3000

CMD bun run main.js
