services:
    web-dev:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.local
        volumes:
            - .:/app
            - /app/node_modules
            - ${BLOG_CONTENTS_DIR}:/app/blog-contents
        ports:
            - 3000:3000
