services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace:cached
            # - /workspace/node_modules
            - ${BLOG_CONTENTS_DIR}:/workspace/blog-contents
        command: sleep infinity
        environment:
            PNPM_HOME: "$HOME/.local/share/pnpm/store"
